### ISSUE TITLE
Delete source options

### ISSUE THREAD

**Issue by ctxhou** [bep/s3deploy#10]
It seems like this lib will delete the s3 data if the uploading data is not matching with s3 current data.

Can you add an options to toggle this feature?
I think most of the user will not think of this package will delete their data.

**Comment by bep** [comment]
>Can you add an options to toggle this feature?

No, I think that would make it another and much simpler product. I welcome PRs that updates the README that can alert the users about this.

**Comment by bep** [comment]
I change my mind about the "usefulness" of this feature. 

If someone wants to add a "--no-delete" flag, I will merge.

**Comment by nathany** [comment]
Maybe the default should be flipped? 

Thing is, this lib will also overwrite files, which can also be destructive.
