### ISSUE TITLE
Invalidating multiple CDN

### ISSUE THREAD

**Issue by lvntbkdmr** [bep/s3deploy#142]
Hello,

Is it possible to invalidate multiple cdn? I'm hosting my website at a S3 bucket with an apex domain (without www) through a CDN. However, for SEO purposes I did not just direct my www subdomain CNAME to same CDN. Instead I created a different S3 bucket that redirect access request to other (main) S3 bucket. It is also served through a different CDN. When I push changes by using s3deploy, it updates my main S3 bucket which is fine, and it also invalidates my main CDN with my apex domain. However, my www subdomain keeps showing older version.

**Comment by bep** [comment]
>Is it possible to invalidate multiple cdn?

No, but your setup looks a little odd to me.

**Comment by lvntbkdmr** [comment]
That setup actually suggested by AWS itself, see Step 2 and 4 => https://docs.aws.amazon.com/AmazonS3/latest/userguide/website-hosting-custom-domain-walkthrough.html

SEO cause of this approach is also menitoned in the Bonus Section of this post => https://nodeployfriday.com/posts/static-website-hosting/

Is it possinle to add invalidation of multiple CDNs here?

**Comment by bep** [comment]
I guess this PR would fix it?

https://github.com/bep/s3deploy/pull/143

**Comment by lvntbkdmr** [comment]
> I guess this PR would fix it?
> 
> #143

Yes I can confirm that it can invalidate multiple CDNs with the updates right now. Thanks !
