### ISSUE TITLE
The -path flag seems to be partially ignored

### ISSUE THREAD

**Issue by rscullin** [bep/s3deploy#19]
I am trying to use the `-path` flag to put my static site in a sub directory of my bucket, as I believe is supported. However, regardless of what I try, all the source files are put in the root of the bucket. Oddly, when specifying a `-path` parameter, `s3deploy` claims that all the files were missing in the destination, regardless of how many times I run the command.

**Repro steps:**
`s3deploy -bucket mydomain.com -path web -region us-east-1 -key AAAA -secret SSS -source public -v -path web/`

**Results:**
All files are in the root of the `mybucket.com` domain. Subsequent runs of the same command shows `Deleted 0 of 0, uploaded X, skipped 0 (100% changed)`, seemingly as if it's looking in the sub directory to see what existed, but then uploading to the root directory.

**Expected results:**
All files are placed in the given path/subdirectory.

**Version/System**
`s3deploy v2, commit none, built at unknown` running on Mac OS X 10.12.6.
Installed via `go get -v github.com/bep/s3deploy` this evening.

**Comment by bep** [comment]
Sorry about that, I missed that in my big rewrite. I have fixed this and added a test for it -- and tested it manually. I will issue a patch release.

**Comment by rscullin** [comment]
Tested and works great. Thanks for the quick fix!
