### ISSUE TITLE
Gziping files makes binary files corrupted

### ISSUE THREAD

**Issue by natrim** [bep/s3deploy#21]
If you set to gzip some files that are not text (ie. .wasm files)

they then have Content-Type: application/x-gzip in S3

making them **not** automatically un-gziped in the browser even with Content-Encoding: gzip
causing errors (as they are still gzipped)

the workaround i am using is to set Content-Type manually, but it gets tedious if you have many of these files as you need to set Content-Type for every extension separately

it would be nice if the s3deploy detected Content-Type **before** gzipping and set it appropriately

**Comment by bep** [comment]
You can set gzip + content type etc. in `.s3config.toml`, but that is maybe not what you're asking about?

**Comment by natrim** [comment]
https://github.com/bep/s3deploy/blob/master/lib/files.go#L196
content-type is detected after gzip, making the resulting type application/x-gzip instead of original type

**Comment by bep** [comment]
Ah, OK, I see.

**Comment by bep** [comment]
Is this something you could fix and create a PR? Most welcome.

**Comment by natrim** [comment]
@bep #22
