### ISSUE TITLE
Resetting so s3deploy will re-upload all the files

### ISSUE THREAD

**Issue by RickCogley** [bep/s3deploy#26]
Hello @bep, thanks for this utility. It works great and even picks up on the awscli settings. Nice! 

A question, I uploaded my files to S3 via an FTP client at first, for testing, then I learned about this. The first time it ran, I could see it appeared to upload everything, and, subsequent runs, I could see that it ran on a delta of files. 

How do I reset it, so that it will "re-upload" everything? Is there a manifest somewhere that it is looking at, that I can delete?

**Comment by bep** [comment]
>Is there a manifest somewhere that it is looking at, that I can delete?

No, that is currently not supported. But we could consider adding a flag.

**Comment by bep** [comment]
Curious, though, why do you want to "re-upload" unchanged files?

**Comment by bep** [comment]
OK, I should have read the documentation, you can do

```bash
s3deploy  -force
```

This should reupload even if unchanged.

**Comment by RickCogley** [comment]
Ah! Thanks!
