### ISSUE TITLE
Update s3 library to use v4 authentication

### ISSUE THREAD

**Issue by halostatue** [bep/s3deploy#3]
Same issue as nathany/s3up#5.

**Comment by nathany** [comment]
Look into https://github.com/aws/aws-sdk-go to see if the syncing will work in a similar way.

**Comment by bep** [comment]
I suppose this should work?

https://nanjekyejoannah.github.io/AWS-if-none-match-header
https://github.com/aws/aws-sdk-go/issues/1269

```go
func WithIfNoneMatch(conditions ...string) request.Option {
    return func(r *request.Request) {
       for _, v := range conditions {
            r.HTTPRequest.Header.Add("If-None-Match", v)
       }
    }
}
svc := s3.New(sess)

svc.PutObjectwithContext(ctx, &s3.PutObjectInput{
    Bucket: aws.String(myBucket),
    Key:      aws.String(myKey),
    Body:    reader,
    // Other parameters...
}, WithIfNoneMatch("etag")
```

I will put it on my list of "things to test":

**Comment by bep** [comment]
The WithIfNoneMatch gives a ` NotImplemented: A header you provided implies functionality that is not implemented`, but the etag validation can be done as today (which is probably the best anyhow).
