### ISSUE TITLE
s3deploy_2.9.0_windows-amd64.zip contains `hugo.exe`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [bep/s3deploy#313]
Thank you for your great project.

I found the content of s3deploy_2.9.0_windows-amd64.zip looks wrong.

```console
$ zipinfo s3deploy_2.9.0_windows-amd64.zip 
Archive:  s3deploy_2.9.0_windows-amd64.zip
Zip file size: 5325529 bytes, number of entries: 3
-rwx---     2.0 fat  9677312 bl defN 80-000-00 00:00 hugo.exe
-rw----     2.0 fat     8488 bl defN 80-000-00 00:00 README.md
-rw----     2.0 fat     1086 bl defN 80-000-00 00:00 LICENSE
3 files, 9686886 bytes uncompressed, 5325183 bytes compressed:  45.0%
```

On the other hand, the content of s3deploy_2.8.1_Windows-64bit.zip looks no problem.

```console
$ zipinfo s3deploy_2.8.1_Windows-64bit.zip 
Archive:  s3deploy_2.8.1_Windows-64bit.zip
Zip file size: 3099348 bytes, number of entries: 3
-rw-r--r--  2.0 unx     1086 bX defN 22-Aug-25 06:33 LICENSE
-rw-r--r--  2.0 unx     7616 bX defN 22-Aug-25 06:33 README.md
-rwxr-xr-x  2.0 unx  9157120 bX defN 22-Aug-25 06:36 s3deploy.exe
3 files, 9165822 bytes uncompressed, 3098940 bytes compressed:  66.2%
```

---

Probably this change is related.

https://github.com/bep/s3deploy/releases/tag/v2.9.0

> We have ported the release script to [Hugoreleaser](https://github.com/gohugoio/hugoreleaser). This means that the archive names have changed (standardised), but it also means that you get only one unviversal, notarized MacOS PKG archive.

**Comment by bep** [comment]
Sorry about this, I will fix ...

**Comment by bep** [comment]
The archive that's there now is correct. It's only the name of the binary (copy of paste mistake), so you can also just rename hugo.exe => s3deploy.exe.

**Comment by suzuki-shunsuke** [comment]
Thank you for your quick fix!
