### ISSUE TITLE
Ignore Sub-folders Feature

### ISSUE THREAD

**Issue by juliano-digitaldesk** [bep/s3deploy#33]
It is possible to ignore folders (local and remote) for a deploy?

What I would like to achieve is to sync everything from a folder, except files in some sub-folder, like "pdf-docs", preserving any remote (in S3) files in this folder.

**Comment by dmulter** [comment]
My use case:

I have separate repos with distinct s3deploy steps that control specific subdirectories of my main static website. For example, /blog, /docs, etc.

I have another repo that handles the main static website that also has an s3deploy step. I would like to configure this deploy to ignore/skip the subdirectories above, as it would wipe them from S3.

**Comment by bep** [comment]
@dmulter I suspect you can do what you want with the `-path` flag

I have one bucket which I use as a "dumping ground" for some test sites, and one example would look like this:

```
s3deploy -source=public/ -region=eu-west-1 -bucket=bep.is -distribution-id=E8OKNT7W9ZYZ2 -path temp/hugotest
```

In that bucket I have several other directories that I deploy separately.

**Comment by dmulter** [comment]
I use `--path` for the subdirectories deploys and they work great. The problem is that the root deploy doesn't use `--path` (since the files need to go to the root), and the lack of the other subdirectories
then causes those whole directories to be deleted.

**Comment by julianoappelklein** [comment]
My use case:
The website is deployed at root, but there are some folders I don't want to touch, like folders that some coworkers use to manually drop large files that are bad to include in the version control system.

**Comment by mpucholblasco** [comment]
@bep, I have free time. I can arrange this if you agree.

**Comment by bep** [comment]
@mpucholblasco that would be great, but we should probably conclude on #37 first -- as it would probably save some "merge work". I'm out and about traveling this week so it will take "some days" before I get to that.

**Comment by mpucholblasco** [comment]
Good idea @bep . Thanks!
