### ISSUE TITLE
Upload no public objects to S3

### ISSUE THREAD

**Issue by mpucholblasco** [bep/s3deploy#38]
When CloudFront is used in together with S3, you can restrict the access to S3 by using an Origin Access Identity (see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html). However, as objects are uploaded with a `public-read` ACL (see https://github.com/bep/s3deploy/blob/master/lib/s3.go#L100), these objects can be accessed directly via S3.

Maybe this is the most used behaviour, however would be nice to parameterise (maybe via yaml config) it.

**Comment by innovia** [comment]
+1

**Comment by bep** [comment]
Does this fix this?

https://github.com/bep/s3deploy/pull/39

**Comment by mpucholblasco** [comment]
Yes, fixed.

Thanks!
