### ISSUE TITLE
No binaries for the 2.10 release

### ISSUE THREAD

**Issue by mreferre** [bep/s3deploy#380]
I have just noticed (due to broken automation on my side) that the s3deploy 2.10.0 release has no binaries available. I can easily work this around and point to the previous release (instead of `latest`) or use the `go` install (which installs 2.10.0). 

But I wanted to report this in case you missed it and you want to fix it.

**Comment by bep** [comment]
Thanks for the heads up ... I will fix.

**Comment by bep** [comment]
I created a 2.10.1 release ... I forgot that I had changed the release process, the build is not triggered by a new release, it's the other way around. This means that there's no binaries for the 2.10.0 release -- I could fix that, but I'd rather not spend the time on it.
