### ISSUE TITLE
Submit binaries to homebrew

### ISSUE THREAD

**Issue by sgtsquiggs** [bep/s3deploy#4]
So I can easily install via `brew install s3deploy` !

**Comment by bep** [comment]
See https://github.com/bep/homebrew-tap/blob/master/Formula/s3deploy.rb

The brew core repo requires to build from source, and that requires a little work that I have not found time to do, yet...

**Comment by bep** [comment]
This works

brew install bep/tap/s3deploy

**Comment by sgtsquiggs** [comment]
It does! Thank you for this.
