### ISSUE TITLE
Environment variable interpolation in config file

### ISSUE THREAD

**Issue by rvangundy** [bep/s3deploy#40]
It would be convenient if you could include environment variables in the YAML config. In particular, I'm trying to set the Expires header which in my case requires a calculated value (the actual date 1 week from now, for example). If you could populate the config file using environment variables you could include any number of dynamic values if necessary.

**Comment by bep** [comment]
I think it would be simpler to use (and possibly also more powerful) if we parsed the config file as a Go text template and added some simple template funcs (so you could do `{{ (.now.Add ...).Format ...}}`. etc.

But I haven't thought too hard about this.

**Comment by bep** [comment]
I added this in a recent commit, but it only understands `${MYENV}` ... See README.
