### ISSUE TITLE
Publish macOS tarball with releases

### ISSUE THREAD

**Issue by glasser** [bep/s3deploy#497]
While `.pkg` files are great for installing a program globally on your machine, they don't work well for more local installations (eg, using something like an `asdf`/`mise` plugin to install a program locally for a project). Would it be possible to provide s3deploy macOS releases in a tarball like you used to, perhaps in addition to the `.pkg`?

**Comment by glasser** [comment]
Thanks!

```
 in /tmp/test-install 󰦜 at 13:35:03-07 ❯ which s3deploy
s3deploy not found

 in /tmp/test-install 󰦜 at 13:35:12-07 ❌1 ❯ mise use ubi:bep/s3deploy --pin
mise /private/tmp/test-install/.mise.toml tools: ubi:bep/s3deploy@v2.12.0

 in /tmp/test-install 󰦜 at 13:35:45-07 ❯ s3deploy -V
s3deploy (devel), commit 0a957c552183a031f6df0938ba4e9dbfdd2b4553, built at 2024-10-17T16:53:26Z

 in /tmp/test-install 󰦜 at 13:35:50-07 ❯ cat .mise.toml 
[tools]
"ubi:bep/s3deploy" = "v2.12.0"
```

**Comment by bep** [comment]
>s3deploy (devel), commit 0a957c552183a031f6df0938ba4e9dbfdd2b4553, built at 2024-10-17T16:53:26Z

Hmm, we should print the release tag there and not `devel`; I guess a leftover from the old Goreleaser setup. I will fix that going forward.
