### ISSUE TITLE
Missing newline in output when enqueuing file

### ISSUE THREAD

**Issue by spinscale** [bep/s3deploy#50]
I am not sure if this is a bug or feature, thus I have not done a PR to fix this.

When running `s3deploy` and a file is marked for uploading, the output looks skewed to me because of a missing newline

```
posts/index.html skipping …
presentations.html (size) ↑ projects.html skipping …
search/feed.rss skipping …
```

The issue is in [deployer.go#L165](https://github.com/bep/s3deploy/blob/master/lib/deployer.go#L165) where a space instead of a newline is used. The space indicates to me that someone thought about this case, so I am hesitant to just send a PR :-)

If it's a feature feel free to close, if it's a bug I am happy to do a famous one liner!

**Comment by bep** [comment]
It's a feature which looks better if you upload hundreds of files.
