### ISSUE TITLE
Prettify output? (Feature request, rather than an issue)

### ISSUE THREAD

**Issue by stephenpiscura** [bep/s3deploy#51]
Please close this issue and forgive me if this out of line. I made [a post in the Hugo forums about this](https://discourse.gohugo.io/t/prettify-output-with-s3deploy/20133), but that seemed to be the wrong place to do so. My question is simple: in the same way that s3deploy runs [HTMLProofer](https://github.com/gjtorikian/html-proofer), could it also be configured to prettify the generated output, perhaps via some other gem or plugin? I think this would be a very welcome feature. Again, my apologies if this is just clogging up your issue queue.

**Comment by bep** [comment]
No, that is outside of the scope of this particular tool.

**Comment by stephenpiscura** [comment]
Ok thanks for your reply.
