### ISSUE TITLE
Feature request: Allow opt in (whitelist) of hidden folders

### ISSUE THREAD

**Issue by boarik** [bep/s3deploy#53]
Example:
The files `.well-known/config.json`, `.well-known/public-key.pem` etc. all reside under the "hidden" folder `.well-known`. We would like to configure the `.well-known` prefix to not be skipped when deploying content to the S3 bucket.

I believe the code responsible for the skip is here: https://github.com/bep/s3deploy/blob/master/lib/deployer.go#L252

**Comment by dltj** [comment]
Whoaboy.  I just ran into this myself.  Hopefully, the author will add this request.  Otherwise I may need to learn Go.
