### ISSUE TITLE
Using Circleci Auto-deploy is suddenly stopped

### ISSUE THREAD

**Issue by itsdeo** [bep/s3deploy#55]
Using the Circleci auto-deploy in Aws S3 is stopped working. Here is the error comes while deploying.

go get -v github.com/bep/s3deploy

Exit code: 1
#!/bin/bash -eo pipefail
go get -v github.com/bep/s3deploy
github.com/bep/s3deploy (download)
package github.com/bep/s3deploy/v2/lib: cannot find package "github.com/bep/s3deploy/v2/lib" in any of:
	/usr/local/go/src/github.com/bep/s3deploy/v2/lib (from $GOROOT)
	/go/src/github.com/bep/s3deploy/v2/lib (from $GOPATH)

Exited with code exit status 1

![Continuous_Integration_and_Deployment](https://user-images.githubusercontent.com/64682377/86787165-6f12b580-c082-11ea-8625-527cc30de25a.png)

**Comment by bep** [comment]
You need to use Go > 1.13 (I guess) and make sure that Go modules is used (it wasn't default in some older Go versions).

If that does not work, I suggest you use one of the binary versions on the release page. Also, if you do want to build from source, you should build from a version tag.
