### ISSUE TITLE
fatal: unable to access 'https://gopkg.in/yaml.v2/': server certificate verification failed. CAfile: none CRLfile: none

### ISSUE THREAD

**Issue by adilbaber** [bep/s3deploy#71]
Looks like github is unable to access gopkg.in cert failing.

**Comment by bep** [comment]
>Looks like github is unable to access gopkg.in cert failing.

You should take that with GitHub. I suggest you try again later.

**Comment by prite36** [comment]
> Looks like github is unable to access gopkg.in cert failing.

It work for me, I change golang version from 1.12 to  golang v1.16
and change form ```go get -v github.com/bep/s3deploy``` to ```go get -v github.com/bep/s3deploy/v2```
